2021-04-13 18:37:36,708 ERROR: Exception on /index [GET] [in /Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/Users/laurenlisle/strava3/app/routes.py", line 63, in index
    return render_template('index.html', title='Home', finished=finished, unfinished=unfinished, n_finished=n_finished, user_id=current_user.id)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/laurenlisle/strava3/app/templates/base.html", line 160, in <module>
    {% extends "bootstrap/base.html" %}
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/laurenlisle/strava3/app/templates/index.html", line 1, in <module>
    {% extends "base.html" %}
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/laurenlisle/strava3/app/templates/base.html", line 160, in <module>
    {% extends "bootstrap/base.html" %}
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 542, in _generate
    return generate(source, self, name, filename, defer_init=defer_init,
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/compiler.py", line 82, in generate
    generator.visit(node)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/compiler.py", line 799, in visit_Template
    self.blockvisit(block.body, block_frame)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/compiler.py", line 378, in blockvisit
    self.visit(node, frame)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/compiler.py", line 846, in visit_Extends
    self.fail('cannot use extend from a non top-level scope',
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: cannot use extend from a non top-level scope
2021-04-13 18:37:36,930 ERROR: Exception on /favicon.ico [GET] [in /Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/Users/laurenlisle/strava3/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/laurenlisle/strava3/app/templates/base.html", line 160, in <module>
    {% extends "bootstrap/base.html" %}
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/laurenlisle/strava3/app/templates/404.html", line 1, in <module>
    {% extends "base.html" %}
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/laurenlisle/strava3/app/templates/base.html", line 160, in <module>
    {% extends "bootstrap/base.html" %}
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 542, in _generate
    return generate(source, self, name, filename, defer_init=defer_init,
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/compiler.py", line 82, in generate
    generator.visit(node)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/compiler.py", line 799, in visit_Template
    self.blockvisit(block.body, block_frame)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/compiler.py", line 378, in blockvisit
    self.visit(node, frame)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/compiler.py", line 846, in visit_Extends
    self.fail('cannot use extend from a non top-level scope',
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: cannot use extend from a non top-level scope
2021-04-13 18:37:37,087 INFO: NHHighPeaks startup [in ./app/__init__.py:75]
2021-04-13 18:38:07,065 INFO: NHHighPeaks startup [in /Users/laurenlisle/strava3/app/__init__.py:75]
2021-04-13 18:38:10,881 INFO: NHHighPeaks startup [in ./app/__init__.py:75]
2021-04-13 18:40:08,424 INFO: NHHighPeaks startup [in /Users/laurenlisle/strava3/app/__init__.py:75]
2021-04-13 18:40:16,616 INFO: NHHighPeaks startup [in ./app/__init__.py:75]
