2021-03-02 19:32:02,210 ERROR: Exception on /favicon.ico [GET] [in /Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 1581, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/Users/laurenlisle/strava3/app/errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/laurenlisle/strava3/app/templates/404.html", line 1, in <module>
    {% extends "base.html" %}
  File "/Users/laurenlisle/strava3/app/templates/base.html", line 20, in <module>
    {% block body %}
  File "/Users/laurenlisle/strava3/app/templates/base.html", line 146, in <module>
    {% block scripts %}
  File "/Users/laurenlisle/strava3/app/templates/base.html", line 155, in <module>
    $.ajax('{{ url_for('notifications') }}?since=' + since).done(
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/helpers.py", line 344, in url_for
    rv = url_adapter.build(endpoint, values, method=method,
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'notifications'. Did you mean 'static' instead?
2021-03-02 19:34:39,280 INFO: NHHighPeaks startup [in /Users/laurenlisle/strava3/app/__init__.py:75]
2021-03-02 19:35:03,519 INFO: NHHighPeaks startup [in ./app/__init__.py:75]
2021-03-02 19:35:30,465 INFO: NHHighPeaks startup [in ./app/__init__.py:75]
2021-03-02 19:36:01,843 INFO: NHHighPeaks startup [in /Users/laurenlisle/strava3/app/__init__.py:75]
2021-03-02 19:36:41,494 INFO: NHHighPeaks startup [in ./app/__init__.py:75]
2021-03-02 19:37:08,659 INFO: NHHighPeaks startup [in ./app/__init__.py:75]
2021-03-02 19:42:35,127 INFO: NHHighPeaks startup [in /Users/laurenlisle/strava3/app/__init__.py:75]
2021-03-02 19:42:39,506 INFO: NHHighPeaks startup [in ./app/__init__.py:75]
2021-03-02 19:43:06,541 INFO: NHHighPeaks startup [in ./app/__init__.py:75]
2021-03-02 19:45:10,218 INFO: NHHighPeaks startup [in /Users/laurenlisle/strava3/app/__init__.py:75]
2021-03-02 19:45:26,340 ERROR: Exception on /welcome [GET] [in /Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/laurenlisle/strava3/app/routes.py", line 30, in welcome
    return render_template('welcome.html', title="Welcome to NH High Peaks")
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/laurenlisle/strava3/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/laurenlisle/strava3/app/templates/welcome.html", line 1, in <module>
    {% extends 'base.html' %}
  File "/Users/laurenlisle/strava3/app/templates/base.html", line 20, in <module>
    {% block body %}
  File "/Users/laurenlisle/strava3/app/templates/base.html", line 144, in <module>
    {% block scripts %}
  File "/Users/laurenlisle/strava3/app/templates/base.html", line 145, in <module>
    {{ super() }}
jinja2.exceptions.UndefinedError: there is no parent block called 'scripts'.
